# Generated by Django 2.1.3 on 2019-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
